services:
  nrf-dev:
  # TODO: Add this container to the github container registry.
    image: nrf-dev
    volumes:
      - .:/workspace/application
    working_dir: /workspace/application
    tty: true