services:
  nrf-dev:
  # TODO: Add this container to the github container registry.
    image: nrf-dev
    volumes:
      - .:/workspace/nrf-bm/apps/container-demo
    working_dir: /workspace/nrf-bm/apps/container-demo
    tty: true